[package]
name = "i2cdev2"
build = "build.rs"
version = "0.4.0"
authors = ["Paul Osborne <osbpau@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/piersfinlayson/rust-i2cdev"
homepage = "https://github.com/piersfinlayson/rust-i2cdev"
documentation = "http://rust-embedded.github.io/rust-i2cdev"
description = """
Provides API for safe access to Linux i2c device interface.

https://www.kernel.org/doc/Documentation/i2c/dev-interface
"""

[dependencies]
libc = "0.2"
bitflags = "1"
byteorder = "1"
nix = "0.11"

[dev-dependencies]
docopt = "0.8"
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"
